security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\Users
        property: username

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      # Suppression de `anonymous: lazy`
      provider: app_user_provider
      form_login:
        login_path: app_login
        check_path: app_login
        default_target_path: redirect_after_login
        always_use_default_target_path: false
        username_parameter: _username
        password_parameter: _password
        enable_csrf: true
        csrf_token_id: authenticate

      logout:
        path: app_logout
        target: app_login

      remember_me:
        secret: "%kernel.secret%"
        lifetime: 604800
        path: /
        always_remember_me: true

  access_control:
    # - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    # - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }
    # - { path: ^/, roles: IS_AUTHENTICATED_FULLY }

when@test:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
      algorithm: auto
      cost: 4
      time_cost: 3
      memory_cost: 10
